<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Aspire.Hosting.Scaleway.Generator</AssemblyName>
        <RootNamespace>Aspire.Hosting.Scaleway.Generator</RootNamespace>
    </PropertyGroup>

</Project>
