using System.Text;

namespace Aspire.Hosting.Scaleway.Generator;

/// <summary>
/// Emits C# source files from parsed TypeScript service definitions.
/// </summary>
public static class CSharpEmitter
{
    private static readonly HashSet<string> SkippedFields =
    [
        "region", "zone", "projectId", "organizationId", "name", "password"
    ];

    /// <summary>
    /// Generates all C# files for a parsed service and writes them to the output directory.
    /// </summary>
    public static void Emit(ParsedService service, string outputDirectory)
    {
        var servicePascal = ToPascalCase(service.Name);
        var category = ServiceCatalog.GetCategory(service.Name);
        var isZonal = ServiceCatalog.IsZonal(service.Name);
        var knownEnums = new HashSet<string>(service.Enums.Select(e => e.Name));

        var serviceOutputDir = Path.Combine(outputDirectory, category, servicePascal);
        Directory.CreateDirectory(serviceOutputDir);

        // Emit enums
        if (service.Enums.Count > 0)
        {
            var enumsContent = EmitEnums(service.Enums, servicePascal);
            File.WriteAllText(Path.Combine(serviceOutputDir, $"Scaleway{servicePascal}Enums.cs"), enumsContent);
        }

        // Emit resources and extensions for each Create*Request
        foreach (var request in service.CreateRequests)
        {
            var resourceName = ExtractResourceName(request.Name);
            var fullResourceName = $"Scaleway{servicePascal}{resourceName}Resource";
            var fullExtensionsName = $"Scaleway{servicePascal}{resourceName}Extensions";

            var resourceContent = EmitResource(request, servicePascal, resourceName, isZonal, knownEnums);
            File.WriteAllText(Path.Combine(serviceOutputDir, $"{fullResourceName}.cs"), resourceContent);

            var extensionsContent = EmitExtensions(servicePascal, resourceName, fullResourceName);
            File.WriteAllText(Path.Combine(serviceOutputDir, $"{fullExtensionsName}.cs"), extensionsContent);
        }
    }

    private static string EmitResource(
        ParsedCreateRequest request, string servicePascal, string resourceName,
        bool isZonal, HashSet<string> knownEnums)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Aspire.Hosting.Scaleway;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Represents a Scaleway {servicePascal} {resourceName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class Scaleway{servicePascal}{resourceName}Resource(string name)");
        sb.AppendLine($"    : Resource(name), IScalewayResource");
        sb.AppendLine("{");
        sb.AppendLine("    public ScalewayCredentialConfig? CredentialConfig { get; set; }");
        sb.AppendLine();
        sb.AppendLine("    public TaskCompletionSource? ProvisioningTaskCompletionSource { get; set; }");

        var hasRegionOrZone = false;

        foreach (var field in request.Fields)
        {
            if (SkippedFields.Contains(field.Name))
            {
                if (field.Name is "region" or "zone")
                {
                    hasRegionOrZone = true;
                }
                continue;
            }

            var csharpType = TypeMapper.MapType(field.TypeScriptType, field.IsOptional, knownEnums);
            if (csharpType is null)
            {
                continue;
            }

            csharpType = TypeMapper.ResolveServicePrefix(csharpType, servicePascal);
            var propertyName = ToPascalCase(field.Name);
            var defaultValue = TypeMapper.GetDefaultValue(csharpType);

            sb.AppendLine();
            if (defaultValue is not null)
            {
                sb.AppendLine($"    public {csharpType} {propertyName} {{ get; set; }} = {defaultValue};");
            }
            else
            {
                sb.AppendLine($"    public {csharpType} {propertyName} {{ get; set; }}");
            }
        }

        // Add Region or Zone property if the request had region/zone fields
        if (hasRegionOrZone)
        {
            sb.AppendLine();
            if (isZonal)
            {
                sb.AppendLine("    public ScalewayZone Zone { get; set; } = ScalewayZone.FrPar1;");
            }
            else
            {
                sb.AppendLine("    public ScalewayRegion Region { get; set; } = ScalewayRegion.FrPar;");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitExtensions(string servicePascal, string resourceName, string fullResourceName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Aspire.Hosting.Scaleway;");
        sb.AppendLine();
        sb.AppendLine("namespace Aspire.Hosting;");
        sb.AppendLine();
        sb.AppendLine($"public static class Scaleway{servicePascal}{resourceName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IResourceBuilder<{fullResourceName}> AddScaleway{servicePascal}{resourceName}(");
        sb.AppendLine($"        this IDistributedApplicationBuilder builder,");
        sb.AppendLine($"        string name)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var resource = new {fullResourceName}(name);");
        sb.AppendLine("        return builder.AddResource(resource);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EmitEnums(List<ParsedEnum> enums, string servicePascal)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace Aspire.Hosting.Scaleway;");

        foreach (var parsedEnum in enums)
        {
            sb.AppendLine();
            sb.AppendLine($"public enum Scaleway{servicePascal}{parsedEnum.Name}");
            sb.AppendLine("{");

            for (var i = 0; i < parsedEnum.Values.Count; i++)
            {
                var value = ToPascalCase(parsedEnum.Values[i]);
                var separator = i < parsedEnum.Values.Count - 1 ? "," : "";
                sb.AppendLine($"    {value}{separator}");
            }

            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Extracts the resource name from a Create*Request type name.
    /// E.g., "CreateInstanceRequest" -> "Instance", "CreateClusterRequest" -> "Cluster".
    /// </summary>
    private static string ExtractResourceName(string createRequestName)
    {
        // Remove "Create" prefix and "Request" suffix
        var name = createRequestName;
        if (name.StartsWith("Create"))
        {
            name = name["Create".Length..];
        }
        if (name.EndsWith("Request"))
        {
            name = name[..^"Request".Length];
        }
        return name;
    }

    /// <summary>
    /// Converts a snake_case or camelCase string to PascalCase.
    /// Also handles kebab-case enum values like 'my-value'.
    /// </summary>
    public static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return input;
        }

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in input)
        {
            if (c is '_' or '-' or ' ')
            {
                capitalizeNext = true;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }
}
