<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireSharedProject>true</IsAspireSharedProject>
        <AssemblyName>Aspire.Hosting.Scaleway</AssemblyName>
        <RootNamespace>Aspire.Hosting.Scaleway</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Aspire.Hosting.Scaleway.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL"/>
        <PackageReference Include="Aspire.Hosting.Redis"/>
    </ItemGroup>

</Project>
