name: Back Office

on:
  push:
    branches:
      - main
    paths:
      - "application/*"
      - "application/shared-kernel/**"
      - "application/shared-webapp/**"
      - "application/back-office/**"
      - ".github/workflows/back-office.yml"
      - "!**.md"
  pull_request:
    paths:
      - "application/*"
      - "application/shared-kernel/**"
      - "application/shared-webapp/**"
      - "application/back-office/**"
      - ".github/workflows/back-office.yml"
      - "!**.md"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Generate Version
        id: generate_version
        run: |
          # Strip leading 0s of Hours and Minutes after midnight
          MINUTE=$(printf "%s" $(date +"%-H%M") | sed 's/^0*//')
          VERSION=$(date +"%Y.%-m.%-d.")$MINUTE
          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Node Modules
        working-directory: application
        run: npm ci

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: application/global.json

      - name: Restore .NET Tools
        working-directory: application
        run: dotnet tool restore

      - name: Restore .NET Dependencies
        working-directory: application
        run: dotnet restore

      - name: Generate and Set User Secret for Token Signing Key
        working-directory: application/shared-kernel/SharedKernel
        run: |
          # Extract UserSecretsId from the .csproj file
          USER_SECRETS_ID=$(grep -oP '(?<=<UserSecretsId>).*?(?=</UserSecretsId>)' SharedKernel.csproj)

          # Generate a 512-bit key and set it as a user secret that can be use for token signing when running tests
          dotnet user-secrets set "authentication-token-signing-key" "$(openssl rand -base64 64)" --id $USER_SECRETS_ID

      - name: Setup Java JDK for SonarScanner
        uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Run Tests with dotCover and SonarScanner Reporting
        working-directory: application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [[ "${{ vars.SONAR_PROJECT_KEY }}" == "" ]] || [[ "${{ vars.SONAR_ORGANIZATION }}" == "" ]] || [[ "${{ secrets.SONAR_TOKEN }}" == "" ]]; then
            echo "SonarCloud is not enabled. Skipping SonarCloud analysis."
            dotnet build back-office/BackOffice.slnf --no-restore /p:Version=${{ steps.generate_version.outputs.version }} &&
            dotnet test back-office/BackOffice.slnf --no-build
          else
            dotnet sonarscanner begin /k:"${{ vars.SONAR_PROJECT_KEY }}" /o:"${{ vars.SONAR_ORGANIZATION }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.dotcover.reportsPaths="coverage/dotCover.html" &&
            dotnet build back-office/BackOffice.slnf --no-restore /p:Version=${{ steps.generate_version.outputs.version }} &&
            dotnet dotcover test back-office/BackOffice.slnf --no-build --dcOutput=coverage/dotCover.html --dcReportType=HTML --dcFilters="+:BackOffice*;+:SharedKernel;-:*.Tests;-:type=*.AppHost.*" &&
            dotnet sonarscanner end
          fi

  code-style-and-linting:
    name: Code Style and Linting
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Node Modules
        working-directory: application
        run: npm ci

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: application/global.json

      - name: Restore .NET Tools
        working-directory: application
        run: dotnet tool restore

      - name: Restore .NET Dependencies
        working-directory: application
        run: dotnet restore

      - name: Build Backend Solution
        working-directory: application
        run: dotnet build back-office/BackOffice.slnf --no-restore

      - name: Run Code Linting
        working-directory: developer-cli
        run: |
          dotnet run lint --backend --self-contained-system back-office | tee lint-output.log

          if ! grep -q "No backend issues found!" lint-output.log; then
            echo "Code linting issues found."
            exit 1
          fi

      - name: Check for Code Formatting Issues
        working-directory: developer-cli
        run: |
          dotnet run format --backend --self-contained-system back-office

          # Check for any changes made by the code formatter
          git diff --exit-code || {
            echo "Formatting issues detected. Please run 'dotnet run format --backend --self-contained-system back-office' from /developer-cli folder locally and commit the formatted code."
            exit 1
          }

      - name: Build Frontend Artifacts
        working-directory: application
        run: npm run build

      - name: Run Lint
        working-directory: application/back-office/WebApp
        run: npm run lint
